### PR TITLE
Simplify

### PR DESCRIPTION
**Pull request by turbolent**
- Use official JDK image
- Use node binary package
- Use latest SBT

@chrisaxiom

### CODE REVIEW

**Comment by chrisaxiom** [comment]
Simple is good 👍  - as long as you have tested it?  Will the sbt download install scala?

**Comment by turbolent** [comment]
Yes, I tested it by building the Knowledge Base Editor, and yes, sbt will automatically download the version of Scala specified in the project's `build.sbt`.

**Comment by chrisaxiom** [comment]
When will it do that though?  Its better to do it sooner (in this file) than later so that other containers can reuse that layer.

**Comment by turbolent** [comment]
Sounds good. I added an `sbt boot exit`, so at least sbt and the scala version for it is downloaded and cached.

**Comment by chrisaxiom** [comment]
👍

**Pull request merged**
